### ISSUE TITLE
move nextjs application to app router

### ISSUE THREAD

**Issue by ysael** [bonfhir/bonfhir#100]

**Comment by julienblin** [comment]
I did some work in this branch: https://github.com/bonfhir/bonfhir/tree/100-move-nextjs-application-to-app-router
The main problem at this point is next-auth: there is a beta version that seems to support app router, but its a bit of a mess. Let's wait a bit that things are adapted properly.

**Comment by julienblin** [comment]
My bad - there is a way to make it work. See the example here: https://github.com/AlleyCorpNord/bonfhir-hackaton
