### ISSUE TITLE
Add helper method for casting a resource

### ISSUE THREAD

**Issue by cadeljones** [bonfhir/bonfhir#112]
Currently when retrieving a referenced resource you are required to cast the resource to get proper type handling

```javascript
(appointment.participant.find(participant => isReferenceOf(participant.actor, 'Practitioner'))?.actor?.included() as Practitioner).name
```

This could made simpler with a helper function such as `asResource` that will cast the resource to the desired type and handle if the resource is not the expected type

**Comment by julienblin** [comment]
Ideally the helper works on simple value, but also on arrays so that filtering is built in.
