### ISSUE TITLE
Add the possibility to get the original ressource from extendResource 

### ISSUE THREAD

**Issue by ysael** [bonfhir/bonfhir#133]
In some cases when for example we need to send a ressource to a bundle, we do not want to send the extra functionality that extendResource will add. 

Ideally we should be able to do something like -> 

```TypeScript

  const patient = new ChamberPatient(patientResource);

  const originalRessource = patient.original;
```

naming TBD

**Comment by ysael** [comment]
@julienblin an other reason why we would want this is that, when passing data from a server component to a client component in nextJs we will get the follow error ->

```Warning: Only plain objects can be passed to Client Components from Server Components. Objects with methods are not supported. Convert it manually to a simple value before passing it to props.```

**Comment by julienblin** [comment]
Yep.
Only thing is that it should probably be a method, that simply calls `toJSON` internally, and added to the final type.
Naming suggestion: `toFhirResource()`, maybe?
