### ISSUE TITLE
Document the `@bonfhir/query` package

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir#155]
Create documentation for the @bonfhir/query https://bonfhir.dev/packages/query

[Complete list of hooks available in the package](https://github.com/bonfhir/bonfhir/tree/main/packages/query/src/r5/hooks)

### TO DO (In order of priority)
- [x] useFhirRead
- [x] useFhirSearch
- [x] useFhirSearchOne
- [x] useFhirSearchAllPages
- [x] useFhirCreateMutation
- [x] useFhirUpdateMutation
- [x] useFhirPatchMutation
- [x] useFhirSaveMutation
- [x] useFhirDeleteMutation
- [x] useFhirExecute
- [x] useFhirExecuteMutation
- [x] useFhirVRead
- [x] useFhirInfiniteSearch
- [x] useFhirGraphql
- [x] useFhirGraphqlResult
- [x] useFhirGraphqlMutation
- [x] useFhirHistory
- [x] useFhirCapabilities
- [x] useFhirTransactionMutation
- ~[ ] useFhirGraph~

**Comment by ianatacn** [comment]
Hi @julienblin ! In the issue description, I've created a list of the hooks to document and attempted to sort them by priority. When you have time, could you please take a look and re-order the hooks as you think is best? I plan to prepare these in batches so the essential queries are documented sooner. Thank you!

**Comment by julienblin** [comment]
@ianatacn - I have re-ordered the hooks in rough order of priorities. You will find that a lot of them behave the same way, so documenting the firsts is long, but the subsequent will be almost identical.

**Comment by julienblin** [comment]
@ianatacn If you don't mind I will try to get this started before you come back from your vacation.

Also - Since there is a dependency, I'll try to complete #103 first and then document appropriately.
