### ISSUE TITLE
Document the `@bonfhir/codegen` package

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir#162]

**Comment by nickvallee** [comment]
@julienblin I want to tackle the documentation for this. Can you describe a use case for `generate` and `copy` script?

Why do we want to generate code definitions, and what the templates in the script?

I think I understand that you run something like this: `npx bonfhir codegen generate --fhir r4b --templates ./file/*`, but I don't fully grasp what this is for.

**Comment by julienblin** [comment]
@nickvallee there are 2 commands currently in the codegen package: `generate` and `copy`.

They both exists to solve the problem of supporting multiple versions of FHIR in the repo, while minimizing the amount of work.

`generate` can load the FHIR structure definition files stored in `packages/codegen/definitions/fhir` and process templates out of it (templates are in the [EJS format](https://ejs.co/)) - you will find an example in the `core` package where we generate the FHIR types using this mechanism (source templates are in the `packages/core/templates` directory, and generate files in the `src/r5` and `src/r4b` directories).

`copy` allows to copy source code from one version to another, while replacing the FHIR versions in import path (e.g. `import "@bonfhir/core/r5" -> "@bonfhir/core/r4b") and allowing some (very clunky) pre-processing (see this for an example: https://github.com/bonfhir/bonfhir/blob/2e042d8dde1efdabf5b5dc1c86638eee24f90556/packages/core/src/r5/formatters.ts#L194)

I think the best way to start is to try to understand the `codegen` and `copyfiles` tasks in the core package.
@cadeljones / @raphaelzin could also probably walk you through it as I believe he is using it for the `n8n` package.

Honestly though, I think this is the most complex package to write documentation for.

**Comment by julienblin** [comment]
This should have been closed by #223.
