### ISSUE TITLE
Refactor n8n Fhir node to regroup by operation

### ISSUE THREAD

**Issue by julienblin** [bonfhir/bonfhir#237]
- Rename "FHIR API"
- Try to align closer to other nodes such as AWS DynamioDB or Contentful
- 1 Operation per FHIR API Operation: https://hl7.org/fhir/http.html
- Search parameters can be a simple text field for now

Implementation remark: might not need codegen if using the `DomainResourceTypes` as the FHIR Subscription node

Instance Level Interactions	
- [ ]  read	Read the current state of the resource
- [ ]  vread	Read the state of a specific version of the resource
- [ ]  update	Update an existing resource by its id (or create it if it is new)
- [ ]  patch	Update an existing resource by posting a set of changes to it
- [ ]  delete	Delete a resource
- [ ]  history	Retrieve the change history for a particular resource

Type Level Interactions
- [ ]  create	Create a new resource with a server assigned id
- [ ]  search	Search the resource type based on some filter criteria
- [ ]  delete	Conditional Delete across a particular resource type based on some filter criteria
- [ ]  history	Retrieve the change history for a particular resource type

**Comment by raphaelzin** [comment]
I implemented the operations `read`, `vread` and `search` so far. I'll work on `create` next.

**Comment by julienblin** [comment]
> I implemented the operations `read`, `vread` and `search` so far. I'll work on `create` next.

Could we get a PR to have a look / integrate current progress?
