### ISSUE TITLE
Allow the use of formatters without the full UI context in React / React Native

### ISSUE THREAD

**Issue by mimi-acn** [bonfhir/bonfhir#291]
# Formatters & UI components 

Formatters should become easily accessible without the overhead of the UI renderers in consumers of React components :
This would allow the current context to still expose the formatters, while giving the opportunity for any type of rendering to occur.

## Todos for the devs
- add a dedicated context for formatters to be reachable through hook(s)
- add warning that the "formatters" in the ui context will get deprecated & link to use new formatters hook(s)
- while the deprecation warning is in effect, formatters in the UI context will be provided under the hood by the "new" hooks / context

## Todos for the Doc
- make sure the deprecated warning gives proper info to the devs
- add documentation on the Provider & hook(s)
- add examples usage for formatters with different UI components libraries, at least the following ones:
  - Gluestack v2
  - Mantine
  - Headless

**Comment by opiation** [comment]
I just merged and published #292. What remains to be done for this ticket to be done?

**Comment by mimi-acn** [comment]
> I just merged and published #292. What remains to be done for this ticket to be done?

The React-Native imports in the Draft PR https://github.com/bonfhir/bonfhir/pull/300

**Comment by opiation** [comment]
Since #300 has been merged, I guess this one is done. :smile:
